CREATE TABLE appointments (
    AppointmentID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    VetID INT(11) DEFAULT NULL,
    PetName VARCHAR(255) NOT NULL,
    OwnerName VARCHAR(255) NOT NULL,
    AppointmentDate DATE NOT NULL,
    AppointmentTime TIME NOT NULL,
    LastUpdatedBy INT(11) DEFAULT NULL,
    added_by INT(11) DEFAULT NULL,
    last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (VetID) REFERENCES veterinarians(VetID),
    FOREIGN KEY (LastUpdatedBy) REFERENCES users(UserID),
    FOREIGN KEY (added_by) REFERENCES users(UserID)
);

CREATE TABLE veterinarians (
    VetID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    VetName VARCHAR(255) NOT NULL,
    LastUpdatedBy INT(11) DEFAULT NULL,
    added_by INT(11) DEFAULT NULL,
    last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (LastUpdatedBy) REFERENCES users(UserID),
    FOREIGN KEY (added_by) REFERENCES users(UserID)
);

CREATE TABLE users (
    UserID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL,
    Username VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    LastUpdated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);